spring.application.name=ninjabank-account-service
server.port=${PORT:8083}

# Neon PostgreSQL Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-royal-dew-b4rst5e7-pooler.c-6.us-east-2.aws.neon.tech:5432/neondb?sslmode=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_b0BSayizAH3m}
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT Secret Configuration
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

# HikariCP Connection Pool Settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000

# JPA & Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
